tests: rewrite
Put some order in the testing flow of the module. In general, xeet uses
a previous version of xeet (one that is probably checked, hopefully),
to test itself. That's the gist of it. A few files are in play here:

1. runtests.sh - runs the suite of tests using a xeet binary out of the
   module virtual environment, probably the system installed one. It
   calls xeet with the xeet.json located at the tests directory.

2. runtests_internal.sh - script used the xeet.json file used by
   runtests. Unless stated otherwise, it activates the virtual
   environment in the repository root, and run a test. Each test is
   actually a xeet invocation, but the one in development.

   If a special environment variable named XEET_PKG_VENV_PATH is set,
   runtests_internal.sh will not use the repository virtual environment,
   but the one set in the variable. This is used mostly for packaging
   tests.

3. run_pkg_tests.sh - for testing packages. Create a separated virtual
   environment, installs xeet from pypi (or it's test counterpart), sets
   XEET_PKG_VENV_PATH to that environment path, and calls runtests.sh.
   So the external xeet is still the system xeet being ran, but xeet in
   the tests themselves is the one in the newly created virtual
   environment.

The tests themselves are the numbered directory. Note that while the
external xeet.json tests should all pass, some of the internal tests
should fail, as tests failures are an important aspect of the test.
Hence - the outer xeet validates that the internal xeet behaves as
expected, including failures.

Signed-off-by: Omer Caspi <omer.caspi@gmail.com>

diff --git a/tests/scripts/runtests b/tests/scripts/runtests
--- a/tests/scripts/runtests
+++ b/tests/scripts/runtests
@@ -1,56 +1,22 @@
 #!/bin/bash
 set -e
 
-_pkg_venv()
+_abort()
 {
-	local repo_flags=""
-
-	[[ -n ${VENV_ACTIVATE} ]] && \
-	    _abort "Virtual environment is activate. Deactivate and run again"
-
-	if [[ ${TEST_PYPI} -eq 1 ]]; then
-	    repo_flags="-i https://test.pypi.org/simple --extra-index-url https://pypi.org/simple/"
-	fi
-	venv_dir=$(mktemp -d)
-	echo "Creating venv at ${venv_dir}"
-	python -m venv ${venv_dir}
-	source ${venv_dir}/bin/activate
-	pip install --upgrade pip
-
-	pip install ${repo_flags} xeet
-}
-
-_fini_pkg_env()
-{
-	deactivate
-	[[ -n ${venv_dir} && -d ${venv_dir} ]] && rm -rf ${venv_dir}
-}
-
-_venv_activate()
-{
-	source ${PROJ_ROOT}/.venv/bin/activate
+	echo "ERROR: $1"
+	exit 1
 }
 
 PROJ_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
-if [ -z "${PROJ_ROOT}" ]; then
-	echo "ERROR: Could not find project root. Are you in the project directory?"
-	exit 1
-fi
+[[ -z "${PROJ_ROOT}" ]] && _abort "Could not find project root. Are you in the project directory?"
 
 HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-cd ${HERE}
+cd ${HERE} || _abort "Could not cd to ${HERE}"
 
-if [[ ${TEST_PKG} -eq 1 ]]; then
-	_pkg_venv
-else
-	_venv_activate
+if [[ -z "${VENV_ACTIVATE}" ]]; then
+	source ${PROJ_ROOT}/.venv/bin/activate || _abort "ERROR: Could not activate virtualenv"
 fi
 
-echo "xeet path: $(which xeet)"
 cmd="xeet run -c xeet.json $*"
 echo "Running: ${cmd}"
 ${cmd}
-ret=$?
-[[ ${TEST_PKG} -eq 1 ]] && _fini_pkg_env
-
-exit ${ret}
